name: mobidoc
version: "0.0.1-dev.0"
description: a Flutter template project for development.
publish_to: none

dependencies:
  auto_route: 7.4.0
  dio: 5.1.1
  elementary: 2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: 2.0.7
  json_annotation: ^4.8.1
  logger: 1.3.0
  path_provider: 2.0.14
  provider: 6.0.5
  retrofit: 4.0.1
  shared_preferences: 2.1.0
  surf_logger: 1.1.0

dev_dependencies:
  auto_route_generator: 7.1.1
  build_runner: 2.3.3
  dart_code_metrics: 5.7.2
  elementary_test: 1.1.3
  flutter_test:
    sdk: flutter
  json_serializable: 6.6.1
  retrofit_generator: 6.0.0+1
  surf_lint_rules: 2.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
